import { test, describe } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";

describe("repository hygiene and naming standards", () => {
  const root = process.cwd();

  test("required documentation and governance files exist", () => {
    const requiredFiles = [
      "README.md",
      "LICENSE",
      "CONTRIBUTING.md",
      "CHANGELOG.md",
      ".gitignore",
      ".gitattributes",
      ".editorconfig",
      ".github/workflows/ci.yml",
    ];

    for (const file of requiredFiles) {
      const fullPath = path.join(root, file);
      assert.ok(fs.existsSync(fullPath), `Required file ${file} must exist`);
    }
  });

  test("no forbidden legacy names exist in project text files", () => {
    const filesToCheck = [
      "README.md",
      "package.json",
      "CONTRIBUTING.md",
      "CHANGELOG.md",
      "src/core/types.ts",
      "src/core/fingerprint.ts",
      "src/cli/help.ts",
      "src/cli/args.ts",
    ];

    const forbiddenPatterns = [
      /\bRepoguard\b/i,
      /\brg_/i,
      /\bRG-\b/,
      /generated by gemini/i,
      /built with ai/i,
    ];

    for (const file of filesToCheck) {
      const fullPath = path.join(root, file);
      if (fs.existsSync(fullPath)) {
        const content = fs.readFileSync(fullPath, "utf-8");
        for (const pattern of forbiddenPatterns) {
          assert.equal(
            pattern.test(content),
            false,
            `Forbidden pattern ${pattern} found in ${file}`
          );
        }
      }
    }
  });
});
